services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=123456

  mysql-db:
    image: mysql
    ports:
      - "6050:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  mongodb-db:
    image: mongo
    restart: unless-stopped
    container_name: mongodb
    ports:
      - 6060:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "6070:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456