services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=123456

  mysql-db:
    image: mysql
    ports:
      - "6050:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456