server:
  port: 8080
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: notification
          uri: lb://notification
          predicates:
            - Path=/notification/**
          filters:
            - StripPrefix=1
#            - AuthFilter

        - id: security
          uri: lb://security
          predicates:
            - Path=/security/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

