server:
  port: 8080
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: security
          uri: lb://security
          predicates:
            - Path=/security/**
          filters:
            - StripPrefix=1

        - id: voyage
          uri: lb://voyage
          predicates:
            - Path=/voyage/**
          filters:
            - StripPrefix=1
            - AuthFilter

        - id: ticket
          uri: lb://ticket
          predicates:
            - Path=/ticket/**
          filters:
            - StripPrefix=1
            - AuthFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

